
export const students = [
  {
    "id": 1,
    "name": "Alice Johnson",
    "age": 21,
    "course_id": 1,
    "username": "Alice.j",
    "password": "s123",
    "profile_pic": require('../assets/profilepic/1.jpg'),
    "address": "123 Maple Street, Springfield",
    "email": "alice.johnson@example.com",
    "phone": "555-123-4567",
    "gender": "Female",
    "blood_group": "O+"
  },
  {
    "id": 2,
    "name": "Bob Smith",
    "age": 22,
    "course_id": 2,
    "username": "bob.smith",
    "password": "securePass456",
    "profile_pic": require('../assets/profilepic/2.jpg'),
    "address": "456 Oak Avenue, Springfield",
    "email": "bob.smith@example.com",
    "phone": "555-234-5678",
    "gender": "Male",
    "blood_group": "A+"
  },
  {
    "id": 3,
    "name": "Charlie Brown",
    "age": 20,
    "course_id": 3,
    "username": "charlie.brown",
    "password": "securePass789",
    "profile_pic": require('../assets/profilepic/3.jpg'),
    "address": "789 Pine Road, Springfield",
    "email": "charlie.brown@example.com",
    "phone": "555-345-6789",
    "gender": "Male",
    "blood_group": "B+"
  },
  {
    "id": 4,
    "name": "Daisy Lee",
    "age": 23,
    "course_id": 4,
    "username": "daisy.lee",
    "password": "securePass101",
    "profile_pic": require('../assets/profilepic/4.jpg'),
    "address": "321 Birch Lane, Springfield",
    "email": "daisy.lee@example.com",
    "phone": "555-456-7890",
    "gender": "Female",
    "blood_group": "AB+"
  },
  {
    "id": 5,
    "name": "Evan Wright",
    "age": 19,
    "course_id": 1,
    "username": "evan.wright",
    "password": "securePass102",
    "profile_pic": require('../assets/profilepic/5.jpg'),
    "address": "654 Cedar Drive, Springfield",
    "email": "evan.wright@example.com",
    "phone": "555-567-8901",
    "gender": "Male",
    "blood_group": "O-"
  },
  {
    "id": 6,
    "name": "Fiona Carter",
    "age": 22,
    "course_id": 3,
    "username": "fiona.carter",
    "password": "securePass103",
    "profile_pic": require('../assets/profilepic/6.jpg'),
    "address": "987 Walnut Way, Springfield",
    "email": "fiona.carter@example.com",
    "phone": "555-678-9012",
    "gender": "Female",
    "blood_group": "B-"
  },
  {
    "id": 7,
    "name": "George Hall",
    "age": 21,
    "course_id": 2,
    "username": "george.hall",
    "password": "securePass104",
    "profile_pic": require('../assets/profilepic/7.jpg'),
    "address": "111 Aspen Court, Springfield",
    "email": "george.hall@example.com",
    "phone": "555-789-0123",
    "gender": "Male",
    "blood_group": "A-"
  },
  {
    "id": 8,
    "name": "Hannah Adams",
    "age": 20,
    "course_id": 4,
    "username": "hannah.adams",
    "password": "securePass105",
    "profile_pic": require('../assets/profilepic/8.jpg'),
    "address": "222 Willow Path, Springfield",
    "email": "hannah.adams@example.com",
    "phone": "555-890-1234",
    "gender": "Female",
    "blood_group": "AB-"
  },
  {
    "id": 9,
    "name": "Ian Baker",
    "age": 23,
    "course_id": 1,
    "username": "ian.baker",
    "password": "securePass106",
    "profile_pic": require('../assets/profilepic/9.jpg'),
    "address": "333 Elm Square, Springfield",
    "email": "ian.baker@example.com",
    "phone": "555-901-2345",
    "gender": "Male",
    "blood_group": "O+"
  },
  {
    "id": 10,
    "name": "Julia Davis",
    "age": 21,
    "course_id": 2,
    "username": "julia.davis",
    "password": "securePass107",
    "profile_pic": require('../assets/profilepic/10.jpg'),
    "address": "444 Cherry Circle, Springfield",
    "email": "julia.davis@example.com",
    "phone": "555-012-3456",
    "gender": "Female",
    "blood_group": "A+"
  },
  {
    "id": 11,
    "name": "Kevin Morris",
    "age": 22,
    "course_id": 3,
    "username": "kevin.m",
    "password": "P108",
    "profile_pic": require('../assets/profilepic/11.jpg'),
    "address": "555 Hickory Grove, Springfield",
    "email": "kevin.morris@example.com",
    "phone": "555-123-4567",
    "gender": "Male",
    "blood_group": "B+"
  },
  {
    "id": 12,
    "name": "Lila Turner",
    "age": 20,
    "course_id": 4,
    "username": "lila.turner",
    "password": "securePass109",
    "profile_pic": require('../assets/profilepic/12.jpg'),
    "address": "666 Maple Avenue, Springfield",
    "email": "lila.turner@example.com",
    "phone": "555-234-5678",
    "gender": "Female",
    "blood_group": "AB+"
  },
  {
    "id": 13,
    "name": "Mason Clark",
    "age": 19,
    "course_id": 1,
    "username": "mason.clark",
    "password": "securePass110",
    "profile_pic": require('../assets/profilepic/13.jpg'),
    "address": "777 Birch Boulevard, Springfield",
    "email": "mason.clark@example.com",
    "phone": "555-345-6789",
    "gender": "Male",
    "blood_group": "O+"
  },
  {
    "id": 14,
    "name": "Nina Edwards",
    "age": 22,
    "course_id": 3,
    "username": "nina.edwards",
    "password": "securePass111",
    "profile_pic": require('../assets/profilepic/14.jpg'),
    "address": "888 Aspen Drive, Springfield",
    "email": "nina.edwards@example.com",
    "phone": "555-456-7890",
    "gender": "Female",
    "blood_group": "B+"
  },
  {
    "id": 15,
    "name": "Oliver Scott",
    "age": 21,
    "course_id": 4,
    "username": "oliver.scott",
    "password": "securePass112",
    "profile_pic": require('../assets/profilepic/15.jpg'),
    "address": "999 Elm Street, Springfield",
    "email": "oliver.scott@example.com",
    "phone": "555-567-8901",
    "gender": "Male",
    "blood_group": "A-"
  },
  {
    "id": 16,
    "name": "Paula White",
    "age": 23,
    "course_id": 2,
    "username": "paula.white",
    "password": "securePass113",
    "profile_pic": require('../assets/profilepic/16.jpg'),
    "address": "111 Willow Court, Springfield",
    "email": "paula.white@example.com",
    "phone": "555-678-9012",
    "gender": "Female",
    "blood_group": "AB-"
  },
  {
    "id": 17,
    "name": "Quinn Walker",
    "age": 20,
    "course_id": 1,
    "username": "quinn.walker",
    "password": "securePass114",
    "profile_pic": require('../assets/profilepic/17.jpg'),
    "address": "222 Cherry Lane, Springfield",
    "email": "quinn.walker@example.com",
    "phone": "555-789-0123",
    "gender": "Male",
    "blood_group": "O+"
  },
  {
    "id": 18,
    "name": "Rachel Young",
    "age": 21,
    "course_id": 3,
    "username": "rachel.young",
    "password": "securePass115",
    "profile_pic": require('../assets/profilepic/18.jpg'),
    "address": "333 Hickory Path, Springfield",
    "email": "rachel.young@example.com",
    "phone": "555-890-1234",
    "gender": "Female",
    "blood_group": "A+"
  }
];
